baseURL = "https://antoineverhulst.com/"
languageCode = "en-us"
title = "Antoine Verhulst"
theme = "paper"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS"]

[params]
  author = "Antoine Verhulst"
  description = "Software Developer & Technical Writer | Open Source Enthusiast"
  keywords = ["portfolio", "blog", "developer"]

  # Home page profile
  name = "Antoine Verhulst"
  bio = "Data Analyst at BlaBlaCar Daily | Data Science & Urban Mobility"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1
  
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
