baseURL = "https://antoineverhulst.com/"
languageCode = "en-us"
title = "Antoine Verhulst"
theme = "adritian"
enableRobotsTXT = true

[module]
[[module.mounts]]
  source = "node_modules/bootstrap/scss"
  target = "assets/scss/bootstrap"

[[module.mounts]]
  source = "node_modules/bootstrap/dist/js"
  target = "assets/js/bootstrap"

[[module.mounts]]
  source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
  target = "assets/js/vendor/bootstrap.bundle.min.js"

[[module.mounts]]
  source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
  target = "assets/css/bootstrap-print.css"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[params]
  title = "Antoine Verhulst - Data and Product Expert"
  description = "Data Product Owner at BlaBlaCar | Data Strategy, Product Development & Public Policy"
  author = "Antoine Verhulst"
  keywords = ["data science", "data product", "product owner", "urban mobility", "transportation economics", "public policy", "data strategy"]
  profileImage = "/img/profile.jpg"

  # Home page settings
  homepageExperienceCount = 6
  mainSections = ["blog"]
  sections = ["intro", "about", "portfolio", "contact"]

[params.blog]
  layout = "sidebar-right"
  sidebarWidth = "25"
  narrowContent = true
  showCategories = true
  showRecentPosts = true
  recentPostCount = 5
  listStyle = "summary"

[params.colorTheme.selector.disable]
  footer = false
  header = false
  mobileHeader = false

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
  URL = "css/custom.css"

# SCSS Plugins
[[params.plugins.scss]]
  URL = "scss/adritian.scss"

[build]
  writeStats = true

[build.buildStats]
  enabledFor = ["scss"]
  disableClasses = false
  disableIDs = false
  disableTags = false
  enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    style = "github"

[taxonomies]
  tag = "tags"
  category = "category"
  skill = "skills"

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Antoine Verhulst'
    weight = 0

[languages.en.menus]
  [[languages.en.menus.header]]
    name = "Home"
    URL = "/"
    weight = 1

  [[languages.en.menus.header]]
    name = "About"
    URL = "#about"
    weight = 2

  [[languages.en.menus.header]]
    name = "Experience"
    URL = "/experience"
    weight = 3

  [[languages.en.menus.header]]
    name = "Portfolio"
    URL = "/client-and-work"
    weight = 4

  [[languages.en.menus.header]]
    name = "Blog"
    URL = "/blog"
    weight = 5

  [[languages.en.menus.header]]
    pre = "email"
    name = "Contact"
    URL = "#contact"
    weight = 6

  [[languages.en.menus.footer]]
    name = "Experience"
    URL = "/experience"
    weight = 1

  [[languages.en.menus.footer]]
    name = "Education"
    URL = "/education"
    weight = 2

  [[languages.en.menus.footer]]
    name = "Portfolio"
    URL = "/client-and-work"
    weight = 3

  [[languages.en.menus.footer]]
    name = "Blog"
    URL = "/blog"
    weight = 4
